on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     os: [macos-latest, ubuntu-latest, windows-latest]
    # runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Prepare test
        run: yarn pretest
      - name: Run test (linux)
        run: xvfb-run -a yarn test
        if: runner.os == 'Linux'
      - name: Run test (other platforms)
        run: yarn test
        if: runner.os != 'Linux'
      - name: Package extension
        run: yarn run vsce package --no-dependencies
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Extension bundle
          path: autometrics**.*
